### ISSUE TITLE
support deleting a check-in

### ISSUE THREAD

**Issue by tsnaik** [tsnaik/helth-bot#16]
people will inevitable click `/helthtoday` sent by other people and that will cause their entry to be added for no good reason.

when we had hastebin bot, everyone kept clicking the command in someone's text for some reason.

so, we need a command to undo or delete a check-in

**Comment by pradhan1234** [comment]
I like this idea, but this would move the onus of removing such dummy updates on the user
How about we have additional filtering captured in the stat computation logic?
We could also have the bot respond to such dummy ping, with appropriate prompt
something like "dummy ping detected, wont be computed towards your update"

**Comment by tsnaik** [comment]
I don't see a way to differentiate.

**Comment by pradhan1234** [comment]
I was thinking something along these lines

Dummy Ping from clicking the command in someone's text 
```
/helthtoday
```

Actual ping that contains update
```
/helthtoday
Activity 1
Activty 2
```

**Comment by tsnaik** [comment]
marking resolved. as we are going with something like `/helth today` to avoid false positive. Which will be tracked in #18
